import Head from "next/head";
import Image from "next/image";
import { useState, useEffect } from "react";
import React from "react";

export default function Home() {
  const [userName, setUserName] = useState()
  const [email, setEmail] = useState()
  const [password, setPassword] = useState()
  const [isLogin, setIsLogin] = useState()
  const [userType, setUserType] = useState()

  const formSubmitHandler = (e: React.SyntheticEvent) => {
    e.preventDefault()
  };

  const inputChangeHandler = (e: React.SyntheticEvent) => {
    const inputEvent = (e.target as HTMLInputElement)
    
  }

  return (
    <>
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>Title</header>
      <form onSubmit={formSubmitHandler}>
        <label>
          Login
          <input type="checkbox" />
        </label>
        <input type="text" placeholder="Username" required/>
        <input type="email" placeholder="email" required/>
        <input type="password" placeholder="password" required/>
        <label>
          <input type="radio" name="userType" required/>
          Normal User
        </label>
        <label>
          <input type="radio" name="userType" required/>
          Admin
        </label>
        <button type="submit">Submit</button>
      </form>
    </>
  )
}
